// Mocks generated by Mockito 5.4.6 from annotations
// in uit_buddy_mobile/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:uit_buddy_mobile/core/error/failures.dart' as _i5;
import 'package:uit_buddy_mobile/features/onboarding/domain/entities/signup_complete_entity.dart'
    as _i8;
import 'package:uit_buddy_mobile/features/onboarding/domain/entities/signup_init_entity.dart'
    as _i6;
import 'package:uit_buddy_mobile/features/onboarding/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:uit_buddy_mobile/features/onboarding/domain/repositories/firebase_repository.dart'
    as _i9;
import 'package:uit_buddy_mobile/features/onboarding/domain/usecases/forget_password_usecase.dart'
    as _i11;
import 'package:uit_buddy_mobile/features/onboarding/domain/usecases/reset_password_usecase.dart'
    as _i12;
import 'package:uit_buddy_mobile/features/onboarding/domain/usecases/signin_usecase.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.SignUpInitEntity>> signUpInit({
    required String? wstoken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpInit, [], {#wstoken: wstoken}),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.SignUpInitEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.SignUpInitEntity>>(
                    this,
                    Invocation.method(#signUpInit, [], {#wstoken: wstoken}),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.SignUpInitEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i8.SignUpCompleteEntity>> signUpComplete({
    required String? signupToken,
    required String? mssv,
    required String? password,
    required String? confirmPassword,
    String? fcmToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpComplete, [], {
              #signupToken: signupToken,
              #mssv: mssv,
              #password: password,
              #confirmPassword: confirmPassword,
              #fcmToken: fcmToken,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, _i8.SignUpCompleteEntity>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, _i8.SignUpCompleteEntity>
                  >(
                    this,
                    Invocation.method(#signUpComplete, [], {
                      #signupToken: signupToken,
                      #mssv: mssv,
                      #password: password,
                      #confirmPassword: confirmPassword,
                      #fcmToken: fcmToken,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i8.SignUpCompleteEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i8.SignUpCompleteEntity>> signIn({
    required String? mssv,
    required String? password,
    bool? rememberMe,
    String? fcmToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #mssv: mssv,
              #password: password,
              #rememberMe: rememberMe,
              #fcmToken: fcmToken,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, _i8.SignUpCompleteEntity>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, _i8.SignUpCompleteEntity>
                  >(
                    this,
                    Invocation.method(#signIn, [], {
                      #mssv: mssv,
                      #password: password,
                      #rememberMe: rememberMe,
                      #fcmToken: fcmToken,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i8.SignUpCompleteEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> forgetPassword({
    required String? mssv,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {#mssv: mssv}),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#forgetPassword, [], {#mssv: mssv}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> resetPassword({
    required String? mssv,
    required String? otpCode,
    required String? newPassword,
    required String? confirmPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #mssv: mssv,
              #otpCode: otpCode,
              #newPassword: newPassword,
              #confirmPassword: confirmPassword,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#resetPassword, [], {
                  #mssv: mssv,
                  #otpCode: otpCode,
                  #newPassword: newPassword,
                  #confirmPassword: confirmPassword,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [FirebaseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseRepository extends _i1.Mock
    implements _i9.FirebaseRepository {
  MockFirebaseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getFcmToken() =>
      (super.noSuchMethod(
            Invocation.method(#getFcmToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Stream<String?> onTokenRefresh() =>
      (super.noSuchMethod(
            Invocation.method(#onTokenRefresh, []),
            returnValue: _i3.Stream<String?>.empty(),
          )
          as _i3.Stream<String?>);
}

/// A class which mocks [SignInUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInUsecase extends _i1.Mock implements _i10.SignInUsecase {
  MockSignInUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i8.SignUpCompleteEntity>> call(
    _i10.SignInParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, _i8.SignUpCompleteEntity>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, _i8.SignUpCompleteEntity>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i8.SignUpCompleteEntity>>);
}

/// A class which mocks [ForgetPasswordUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordUsecase extends _i1.Mock
    implements _i11.ForgetPasswordUsecase {
  MockForgetPasswordUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(
    _i11.ForgetPasswordParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [ResetPasswordUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUsecase extends _i1.Mock
    implements _i12.ResetPasswordUsecase {
  MockResetPasswordUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(
    _i12.ResetPasswordParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}
