import 'package:uit_buddy_mobile/core/network/api/api_response.dart';
import 'package:uit_buddy_mobile/features/profile/data/datasources/post_datasource_interface.dart';
import 'package:uit_buddy_mobile/features/profile/data/models/post_model.dart';

class PostDatasourceImpl implements PostDatasourceInterface {
  @override
  Future<ApiResponse<List<PostModel>>> getPosts() async {
    try {
      await Future.delayed(const Duration(milliseconds: 500));

      final apiResponse = ApiResponse<List<PostModel>>(
        data: [
          PostModel(
            id: '1',
            user: UserEntity(
              name: 'Minh Hoàng',
              homeClass: 'KTPM2023.1',
              avatarUrl: 'assets/images/sample/f1.jpg',
            ),
            content: 'Just finished my Machine Learning project! The neural network finally achieved 95% accuracy. Anyone else working on AI projects this semester?',
            mediaUrls: ['https://picsum.photos/seed/ml_project/600/400', 'https://picsum.photos/seed/github_repo/600/300'],
            likeCount: 10,
            commentCount: 5,
            shareCount: 2,
            createdAt: DateTime(2026, 3, 12, 7, 30),
          ),
          PostModel(
            id: '2',
            user: UserEntity(
              name: 'Minh Hoàng',
              homeClass: 'KTPM2023.1',
              avatarUrl: 'assets/images/sample/f1.jpg',
            ),
            content: 'Just finished my Machine Learning project! The neural network finally achieved 95% accuracy. Anyone else working on AI projects this semester?',
            mediaUrls: ['https://picsum.photos/seed/github_repo/600/300'],
            likeCount: 10,
            commentCount: 5,
            shareCount: 2,
            createdAt: DateTime(2026, 3, 12, 7, 30),
          ),
          PostModel(
            id: '3',
            user: UserEntity(
              name: 'Minh Hoàng',
              homeClass: 'KTPM2023.1',
              avatarUrl: 'assets/images/sample/f1.jpg',
            ),
            content: 'Just finished my Machine Learning project! The neural network finally achieved 95% accuracy. Anyone else working on AI projects this semester?',
            mediaUrls: [],
            likeCount: 10,
            commentCount: 5,
            shareCount: 2,
            createdAt: DateTime(2026, 3, 12, 7, 30),
          ),
        ],
        message: 'Posts fetched successfully.',
        statusCode: 200,
      );
      return apiResponse;
    } catch (e) {
      return Future.value(ApiResponse<List<PostModel>>(
        data: null,
        message: 'Failed to fetch posts.',
        statusCode: 500,
      ));
    }
  }
}

//which model is posting these inline suggestions?
// The inline suggestions are generated by an AI language model, specifically OpenAI's GPT-3.5.