name: UIT Buddy AppMobile CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-codebase:
    name: Lint, Format and Test Code
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.38.6"
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Create google-services.json
        run: echo '${{ secrets.GG_SERVICES }}' > android/app/google-services.json

      - name: Create key.properties
        run: echo '${{ secrets.KEY_PROPERTIES }}' > android/key.properties

      - name: Run Build Runner
        run: dart run build_runner build --delete-conflicting-outputs -v

      - name: Verify Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze Code (Linting)
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Run Unit Tests
        run: flutter test test/ --no-pub

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Current Date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.38.6"
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Create google-services.json
        run: echo '${{ secrets.GG_SERVICES }}' > android/app/google-services.json
      - name: Create key.properties
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties

      - name: Run Build Runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Create Runtime .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Build APK
        run: |
          flutter build apk --release \
            --build-name=v1.0.${{ github.run_number }}-${{ env.CURRENT_DATE }} \
            --build-number=${{ github.run_number }} \
            --dart-define-from-file=.env

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: tester
          file: build/app/outputs/flutter-apk/app-release.apk
          releaseNotes: "Auto-build v1.0.${{ github.run_number }}-${{ env.CURRENT_DATE }}"
